@baseUrl = http://localhost:3000

### Login the default user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "login": "zaza@student.vinci.be",
  "password": "mdp1"
}

> {%
  client.global.set("user", response.body.token);
%}

### Login the default user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "login": "zuzu@student.vinci.be",
  "password": "mdp1"
}

> {%
  client.global.set("user", response.body.token);
%}

### Get one stage by user id
GET {{baseUrl}}/stages/stageByUserId
Content-Type: application/json
Authorization: {{user}}

