@baseUrl = http://localhost:3000

### Login the default user
POST http://localhost:3000/auths/login
Content-Type: application/json

{
    "login": "zuzu@student.vinci.be",
    "password": "mdp1"
}

> {%
  client.global.set("user", response.body.token);
%}

### Get all the users
GET http://localhost:3000/users
Content-Type: application/json
Authorization: {{user}}

### Register a new user
POST http://localhost:3000/auths/register
Content-Type: application/json

{
     "login": "robert.ailenei@student.vinci.be",
     "password": "mdp1",
     "fname": "sef gtgt",
     "lname": "dzzdq",
     "phoneNum": "0477777777"
}