@baseUrl = http://localhost:3000

### Login the default user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "login": "zuzu@student.vinci.be",
    "password": "mdp1"
}

> {%
  client.global.set("user", response.body.token);
%}

### Get all the users
GET {{baseUrl}}/users/getAll
Content-Type: application/json
Authorization: {{user}}

### Register a new empty user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{

}

### Register a new user with empty attributes
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "login": "",
   "password": "",
      "f_name": "",
      "l_name": "",
      "role": "",
  "phone_number": ""

}

### Register a new user with some empty attributes
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "login": "zaza",
  "password": "zaza",
  "f_name": "zaza",
  "l_name": "zaza",
  "role": "zaza",
  "phone_number": ""
}

### Register a new user with no empty attributes
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "login": "zaza@vinci.be",
  "password": "zaza",
  "f_name": "zaza",
  "l_name": "zaza",
  "role": "zaza",
  "phone_number": "0484118694456"
}

### Register a new user with wrong role
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "login": "zaza@vinci.be",
  "password": "zaza",
  "f_name": "zaza",
  "l_name": "zaza",
  "role": "etudiant",
  "phone_number": "0484118694456"
}

### Register a new user with good role
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "login": "zaza@vinci.be",
  "password": "zaza",
  "f_name": "zaza",
  "l_name": "zaza",
  "role": "administratif",
  "phone_number": "0484118694456"
}


