@baseUrl = http://localhost:3000

### Login the default user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "login": "mia.liae@student.vinci.be",
    "password": "mdp1"
}

### Get all the users
GET {{baseUrl}}/users
Content-Type: application/json

### Register a new user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
     "login": "ali.elhannouti@student.vinci.be",
     "password": "mdp1",
     "fname": "Ali",
     "lname": "Elhannouti",
     "phoneNum": "0477777777"
}